languageCode = "en"
languageName = "English"
weight = 1
title = "Glinek"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "Glinek's portfolio website"
dateFormat = "2 January 2006"
copyright = "© 2024 Szymon Glinka | This website does NOT use any cookies for tracking."
logo = "logo_justBallv2.png"

[params.author]
name = "Simon aka. Glinek"
image = "avatar.jpg"
headline = "18yo robotics engineering student and a maker"
bio = "18yo robotics engineering student, currently heavy machinery mechanic"
links = []
