[[main]]
name = "Home"
pageRef = "index"
identifier = "KCgx6vYcpW"
weight = 1

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "eAnHAPmV1V"
weight = 2

[[main]]
name = "Organizations&Teams"
pageRef = " "
identifier = "ot"
weight = 3

[[main]]
name = "TNST"
pageRef = "tnst"
identifier = "JCwfHekekU"
parent = "ot"
weight = 9999

[[main]]
name = "ANUlab"
pageRef = "anulab"
identifier = "5IYwsjgDTd"
parent = "ot"
weight = 9999

[[main]]
name = "About Me"
pageRef = "about"
identifier = "oH3nAxdPVc"
weight = 5

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "DfnzlEa6HX"
weight = 6

[[main]]
pre = "github"
url = "https://github.com/Szymon-Glinka"
identifier = "nvumXsWy43"
weight = 9999





[[footer]]
none = "none"
