colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
defaultBackgroundImage = "."

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "2"
showMoreLink = true
showMoreLinkDest = "./projects"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "basic_v3-1.png"

[article]
showDate = true
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = false
showSummary = true
showZenMode = false
showRelatedContent = ""

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]
